numprogress:
	deno run --allow-all ./progress.ts

simprogress:
	deno run --allow-all ./progress2.ts

comprogress:
	deno run --allow-all ./comprogress.ts

inquier:
	deno run --allow-all ./inquier.ts

loading:
	deno run --allow-all ./loading.ts